### ISSUE TITLE
https://beta.mozilla.org/ downloads a 32-bit full installer on 64-bit windows; should download stub or arch-appropriate installer

### ISSUE THREAD

**Issue by gijsk** [mozilla/bedrock#10336] opened 2021-07-16 15:04 UTC
## Description

I set up a new Windows machine, and a while later, when I happened to look at task manager, realized I'd installed a 32-bit copy of Firefox on my fancy 64-bit machine, which is sad.

### Steps to reproduce

STR:

1. in MS edge on 64-bit Windows on a 64-bit machine, open https://beta.mozilla.org/
2. you get redirected to https://www.mozilla.org/en-GB/firefox/channel/desktop/#beta (or some localized variation thereof)
3. click the "Download" link next to "Beta" (which is scrolled slightly underneath the header at the top, fwiw)
4. inspect the installer, and/or run it and inspect the result

### Expected result

64-bit Firefox should be installed!

### Actual result

32-bit Firefox was installed. :-(

### Environment

Win10 2020H2, Edge, 64-bit threadripper blah-die-blah machine.

**Comment by alexgibson** [comment] 2021-07-16 15:05
I think this is a duplicate of https://github.com/mozilla/bedrock/issues/10194

**Closed** 2021-07-16 15:05 UTC
Labels: Bug :bug:
