### ISSUE TITLE
RSS Feed for application relases?

### ISSUE THREAD

**Issue by AdrianKoshka** [mozilla/bedrock#5550] opened 2018-04-03 06:45 UTC
It'd be really handy to have an RSS feed for releases of applications like Thunderbird and Firefox available from the mozilla.org website.

**Comment by kyoshino** [comment] 2018-04-03 12:11
This is being discussed in [Bug 1449884](https://bugzilla.mozilla.org/show_bug.cgi?id=1449884).

**Comment by alexgibson** [comment] 2018-04-03 13:08
Closing this as a duplicate of the bug linked above.

**Closed by alexgibson** 2018-04-03 13:08 UTC
