### ISSUE TITLE
Styling issue with picto card in /firefox/channel/desktop

### ISSUE THREAD

**Issue by kgeorgiou** [mozilla/bedrock#9053] opened 2020-06-25 05:17 UTC
## Description

In the [Firefox Download page](https://www.mozilla.org/en-US/firefox/channel/desktop/), there's a stray list item bullet showing on the [picto card](https://protocol.mozilla.org/patterns/molecules/picto-card.html):

**Safari:**
<img width="500" alt="ff-channel-safari" src="https://user-images.githubusercontent.com/4765455/85656541-de4dda00-b67e-11ea-8a1f-747ae6485cb1.png">
**Chrome:**
<img width="500" alt="ff-channel-chrome" src="https://user-images.githubusercontent.com/4765455/85656580-ea399c00-b67e-11ea-961c-531256bdd38e.png">

### Steps to reproduce

1. Visit https://www.mozilla.org/en-US/firefox/channel/desktop/
2. Scroll a down a bit, right before the newsletter form

### Expected result

A list item bullet shouldn't be visible

### Actual result

A list item bullet is visible

### Environment

macOS 10.14
Safari Version 13.1 / Chrome Version 83.0

### Notes

I believe I have a fix for this specific case here https://github.com/kgeorgiou/bedrock/commit/ca77a426f848ebf6e4fe2090a7bc91ec86973649, but I think this might be a broader issue throughout the site.

Also not sure why the [default base element](https://github.com/mozilla/bedrock/blob/0f3bb17414d7697d7fee8290651960b50a5e55bf/bedrock/base/templates/macros-protocol.html#L200) for the picto card in bedrock is 'li' whereas in the [design system](https://protocol.mozilla.org/patterns/molecules/picto-card.html) is 'section'.

**Comment by alexgibson** [comment] 2020-06-25 12:33
Clusing as a duplicate of https://github.com/mozilla/bedrock/issues/8501

Thanks for reporting nonetheless :)

**Closed by alexgibson** 2020-06-25 12:33 UTC
