### ISSUE TITLE
[FFYR #2] - Privacy Notice update

### ISSUE THREAD

**Issue by djst** [mozilla/bedrock#6198] opened 2018-09-19 17:32 UTC
FFYR priority #2
https://docs.google.com/presentation/d/1GVQ94lVChlPnbTYgG56wJ-UblkraIfMHJxqYD9KvSOQ/edit#slide=id.g3f2e52f863_0_2

Work should kick off formally with a meeting including David, UX, dev, copy and stakeholder Daniel Kessler (who has input on what we might do). 

Success Criteria:
- [x] Page is ported page to Protocol
- [ ] headline is updated to be eye-catching copy that speaks to FFYR
- [ ] Paragraph below heading is removed
- [x] Accordion is removed
- [ ] Is vetted/approved by:
Product - TBD
FMB - Maura
Mozilla Brand - Daniel 
Legal - TBD (MFeldman)
- [ ] Live by date x 
- [ ] a/b test is in place for copy variations

Risks:
- [ ] Legal review of copy

**Comment by ejregithub** [comment] 2018-10-02 23:31
Sent invite for kickoff meeting for Wed Oct 3rd

**Comment by dzingeek** [comment] 2018-10-04 23:16
Talked w/Natalie today about FFYR headline(s). We will sync up Tuesday next week to see where she is.

**Comment by djst** [comment] 2018-10-05 07:37
@alexgibson can move forward with rewriting the page to use Protocol components, including expanding/removing the accordion boxes and show the full text instead.

**Comment by dzingeek** [comment] 2018-10-05 19:12
@alexgibson this is great work, it already looks better. Let's sync up in a mini working session to hash out some mini design tweaks when we both have availability.

**Comment by alexgibson** [comment] 2018-10-17 08:54
@dzingeek any objections to moving forward with this as-is? We can revisit copy and A/B tests later if this is a good enough default going forward.

**Comment by dzingeek** [comment] 2018-10-17 15:38
@alexgibson let's keep it as is so it's as close to the previous design as possible. As far as moving forward with this I am good with it but let's have @djst make that call. 

Also, I kicked this off with Clay yesterday so we should check in with him to see when he will have some headlines for us to look at.

**Comment by djst** [comment] 2018-10-18 08:01
Hey @alexgibson, if the question is "can we push this out as is and treat the copy A/B test as a separate card, I'm good with that assuming that card gets created. Or this card is kept open and stays in In Progress, either way works for me.

**Comment by alexgibson** [comment] 2018-10-18 08:03
@djst Yes we can do that and keep this issue open.

**Comment by alexgibson** [comment] 2018-10-22 13:34
Ok, the base privacy page updates are now merged, so we're good to start iterating on copy & design.

**Comment by dzingeek** [comment] 2018-10-23 18:38
Copy is still in progress due to Clay being new and Natalie being on PTO. 

Clay will be syncing up with Janis this Thursday (10.25.18) to get a better understanding of our new messaging and then he will start working on this.

**Comment by djst** [comment] 2018-10-24 12:51
What's the status here? Also, is Clay not in Github yet?

**Comment by amychurchwell** [comment] 2018-10-24 15:18
@djst he is, his username is @clay-chaffin

**Comment by rraue** [comment] 2018-10-30 10:05
We should measure improvement on this page and in order to do so, we need to gather data before we update. My suggestion would be to meassure scrolling on this page to see if the new messaging/design leads to more users reading/scrolling and spending more time on this/clicking the nav.

What do you think @dzingeek and is this possible and feasible Xuan (cant find your github handle)?

**Comment by dzingeek** [comment] 2018-10-30 18:03
Sounds good @rraue let me see what I can dig up via GA.

**Comment by dzingeek** [comment] 2018-10-30 18:15
Quick High-level GA:

**Overview**
<img width="1377" alt="screen shot 2018-10-30 at 11 09 12 am" src="https://user-images.githubusercontent.com/3740746/47740329-c701e380-dc34-11e8-90b2-87f2865f4e19.png">

**Event Actions**
<img width="1367" alt="screen shot 2018-10-30 at 11 12 13 am" src="https://user-images.githubusercontent.com/3740746/47740334-c9643d80-dc34-11e8-8cbf-f0a144eae5d9.png">

**Something to note.** If I am reading this right it looks like a big chunk of users who already have Fx come here and click on the Fx Download button in the nav...this seems odd. Unless they are updating to the latest version of Fx.

**Comment by clay-chaffin** [comment] 2018-10-30 18:17
Copy update: I'm working on the headline(s) at 3pm today with Natalie

**Comment by xluo-mozilla** [comment] 2018-10-31 16:40
@rraue not sure whether it's feasible or not to measure how long the user scroll down on this page, and I will spend some time probably early next week to look into that. 
@dzingeek will also check why existing FxA users still come to this page.

**Comment by stephaniehobson** [comment] 2018-10-31 17:39
The browser opens the privacy notice page by default under certain conditions. Not sure what they are.

**Comment by alexgibson** [comment] 2018-11-01 09:20
> @rraue not sure whether it's feasible or not to measure how long the user scroll down on this page, and I will spend some time probably early next week to look into that.

We can do this using JS if we need to, although there is a certain irony about scroll tracking people on a page that's all about privacy. As long as it's only a temporary thing, I think we could still do it if it was really the only way to measure engagement.

> The browser opens the privacy notice page by default under certain conditions. Not sure what they are.

Firefox opens `/privacy/firefox/` as a second tab (along with `about:welcome`) the first time it's opened using a new profile.

**Comment by djst** [comment] 2018-11-01 11:04
To keep implementation simple, wouldn't it be enough to just track whether someone scrolls or not and look for an increase in total scroll rate? 

(@agibson in response to the privacy irony remark, I see your point but think GA is simply part of our privacy policy so the second the page loads, there's a baseline creepiness factor that we just can't escape. I don't think tracking how someone scrolls is necessarily creepier than tracking around where they're from, what OS they're using, whether they bounce or engage on the page, etc.)

**Comment by alexgibson** [comment] 2018-11-01 11:38
For every other web page I would agree here @djst, but I think it’s important to consider that this is literally the first page that Firefox opens with a fresh profile. The user has no chance to opt out here, whereas they would with subsequent page visits. I’m not saying let’s not do this, just that we should make sure it’s absolutely necessary.

**Comment by djst** [comment] 2018-11-01 13:00
Yeah I'm with you. And I think tracking scroll length is not necessary anyway (unless @rraue strongly feels otherwise); it should be sufficient to just at a tag for when a scroll event triggers.

**Comment by rraue** [comment] 2018-11-01 13:28
I agree and that’s what I meant. Any event indicating that the page was
used in any way would be great. We don’t need scroll depth just if or if
not.

-- 
______
Send via mobile

Raphael Raue
Global Head of Seo
www.mozilla.org

twitter.com/raue

**Comment by dzingeek** [comment] 2018-11-01 18:02
Will measuring time on page not be enough? I mean right now it's like 20 seconds or so.

**Comment by djst** [comment] 2018-11-01 21:49
Exactly. That's the ask: to have the tagging in GTM/GA before a new heading
is introduced. By at least a few days.

Den tor 1 nov. 2018 22:47 skrev Stephanie Hobson <notifications@github.com>:

**Comment by alexgibson** [comment] 2018-11-02 08:17
On existing pages of the site where we do scroll tracking, such as on `/firefox`, we tag scroll events as `non-interactive` so as to not effect the bounce rate. We should probably follow suit and do the same here. If we do that, I don’t think it should need to be done ahead of an A/B test but we can confirm with AP.

**Comment by rraue** [comment] 2018-11-02 13:07
@alexgibson On most pages scroll is just a non-interaction and shouldn't change the bounce rate but on this page scroll is basically the goal, without a cta. So scrolling should be counted as a non-bounce.

**Comment by alexgibson** [comment] 2018-11-02 13:11
@rraue not sure I follow? That kinda backs up what I'm suggesting we do, unless I'm not understanding what you're saying.

**Comment by rraue** [comment] 2018-11-02 13:17
I wanted to point out, I think scroll on this page should be not a non-interaction but an active interaction changing the bounce rate by design. If somebody scrolls it should be not a bounce. 

I understood you want to set it on this page as well as a non-interaction. Apology if I understood you wrong.

**Comment by alexgibson** [comment] 2018-11-02 13:19
> I wanted to point out, I think scroll on this page should be not a non-interaction but an active interaction changing the bounce rate by design. If somebody scrolls it should be not a bounce.

Ah, ok i see now - so we want and interactive event, and we **do** want it to effect the bounce rate. Thanks 👍

**Comment by rraue** [comment] 2018-11-02 13:21
But I give you that, we should do this very carefully so its only on informational pages which have no other clear cta so we do not mess with our data.

**Comment by dzingeek** [comment] 2018-12-12 18:49
I don't think we ever got copy. Let me check with Natalie as she was the one working on it a while back.

**Comment by ejregithub** [comment] 2019-02-04 21:34
Closing per discussion w. Justin C

**Closed by ejregithub** 2019-02-04 21:34 UTC
Labels: In Sprint, Moz.org
