### ISSUE TITLE
Fraud Report page returns 500 Something went wrong.

### ISSUE THREAD

**Issue by Standard8** [mozilla/bedrock#9176] opened 2020-07-19 18:31 UTC
## Description

Visited https://www.mozilla.org/en-US/about/legal/fraud-report/, submitted a report.

When I submitted it came up with "Something went wrong" and 500 in the title.

### Steps to reproduce

* Filled out the form and pressed submit.

For the form fill-out, I set

* url -> Filled out with a url I was reporting.
* Category -> "Distributing modified Firefox/malware"
* Product -> Other
* Name a more specific product -> Firefox Focus
* Please provide addition details -> Filled out with some text.
* Email Address -> Added my MoCo email.

### Expected result

Submit without errors.

### Actual result

Something went wrong.

### Environment

Firefox Nightly 80.0a1 (2020-07-19) (64-bit) on Mac.

**Comment by ejregithub** [comment] 2020-07-19 21:52
I attempted this in 78.0.2 and was not able to replicate the error. I then attempted to replicate the error in Nightly 80.0a1 (2020-07-18) (64-bit) and could not do so. Realizing I was not on the latest Nightly build I updated to 80.0a1 (2020-07-19) (64-bit) and tested again, also finding no issues. WFM.

**Comment by alexgibson** [comment] 2020-07-20 08:33
I was able to reproduce this issue shortly after the bug was filed over the weekend, but am also unable to do so now.

I did manage to find the error in Sentry: https://sentry.prod.mozaws.net/operations/bedrock-prod/issues/9146092/, which gives the following error when trying to send the email:

```
SMTPAuthenticationError: (535, b'Authentication Credentials Invalid')
```

Anything we should look at here, @pmac?

**Comment by duallain** [comment] 2020-07-20 16:24
It looks like the EU cluster's SES credential wasn't successfully rotated a few weeks back.  I took a look after this bug was filed and finished the work. (Reapplied the new secret).  It should be good now.  Planning on keeping an eye on that type of error in sentry to ensure it's fixed for good. 

Closing the ticket now, please let me know if for whatever reason that doesn't make sense.

**Closed by duallain** 2020-07-20 16:24 UTC
Labels: Bug :bug:
