### ISSUE TITLE
Extract strings for SEO browser comparison - Firefox vs Google Chrome

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8318] opened 2019-12-16 16:02 UTC

**Comment by ejregithub** [comment] 2020-01-06 23:17
Noting the go ahead (Raphael approved) to add new copy & links between each section and a download button at the bottom of the page.

**Comment by hoosteeno** [comment] 2020-01-08 19:04
Duplicate of #8319

**Closed by hoosteeno** 2020-01-08 19:04 UTC
Labels: Standard
