### ISSUE TITLE
[10/4] FFYR homepage card updates

### ISSUE THREAD

**Issue by djst** [mozilla/bedrock#6196] opened 2018-09-19 17:22 UTC
This work supports the Fight for Your Rights campaign

Success Criteria:

    New cards live on 10/4 (content delivered from FMB/MJ)

Currently blocked on specific cards from MJ

**Comment by alexgibson** [comment] 2018-09-26 12:31
@djst is this a duplicate of https://github.com/mozilla/bedrock/issues/6154 ?

**Comment by ejregithub** [comment] 2018-09-26 13:27
@alexgibson @djst - yes, this is a dup to 6154, closing this one

**Closed by ejregithub** 2018-09-26 13:27 UTC
Labels: Fx Master Brand
