### ISSUE TITLE
QR code with incorrect destination URL

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#5740] opened 2018-05-25 13:31 UTC
https://bugzilla.mozilla.org/show_bug.cgi?id=1462941

/cc @ejregithub

**Comment by kbrosnan** [comment] 2018-05-25 20:18
The issue is that there are two different apps in the Play store. [Firefox Focus](https://play.google.com/store/apps/details?id=org.mozilla.focus) available in most of the world and [Firefox Klar](https://play.google.com/store/apps/details?id=org.mozilla.klar) in three countries; Germany, Austria, and Switzerland.

As the apps have different IDs you would need to geolocate the user before supplying them with the correct qr code. I don't know if there is a way to create a URL that will auto redirect users to the correct app.

**Comment by ejregithub** [comment] 2018-05-25 21:28
@kbrosnan  - we do have geolocation in place on /whatsnew, which makes this a curiosity.

The conditional content (based on the user being logged into their Firefox account and synced to multiple devices) in the page shows the Focus CTA (or Klar based on geolocation) and the QR code is configured with this URL https://mzl.la/2joPGS8

**Comment by alexgibson** [comment] 2018-05-31 12:54
> @kbrosnan - we do have geolocation in place on /whatsnew, which makes this a curiosity.

> The conditional content (based on the user being logged into their Firefox account and synced to multiple devices) in the page shows the Focus CTA (or Klar based on geolocation) and the QR code is configured with this URL https://mzl.la/2joPGS8

It looks like in the page we're not using geolocation (I can't see this as a requirement in the original bug for /whatsnew 60). 

- We have a single QRCode for only for Focus.
- The iOS app store badge has a link to Klar, for the `de` locale only.
- The Android Play Store badge has a single link only for Focus.

ref: https://github.com/mozilla/bedrock/blob/master/bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx60.html#L101-L119

**Comment by ejregithub** [comment] 2018-05-31 18:44
Adding Craig here as this needs to be fixed in WNP 61, if not before.

**Comment by alexgibson** [comment] 2018-11-05 13:32
Was this fixed in WNP 61, can this issue be closed?

**Comment by craigcook** [comment] 2018-11-16 16:17
Whatsnew61 does have separate QR codes for Focus and Klar, and uses geolocation to reveal Klar content in Germany, Austria, and Switzerland (regardless of language). So I think this is resolved, we just neglected to close it.

**Closed by craigcook** 2018-11-16 16:17 UTC
Labels: Fx Existing User aDAU
