### ISSUE TITLE
ESR firstrun shows an out of date message

### ISSUE THREAD

**Issue by mkaply** [mozilla/bedrock#7325] opened 2019-06-14 20:54 UTC
Note this was opened previously - https://github.com/mozilla/bedrock/issues/6495 - I'm definitely seeing this,.

## Description

When going to https://www.mozilla.org/en-US/firefox/60.7.0/firstrun using the latest ESR (60.7), there is a "Your Firefox is out-of-date" message.

### Steps to reproduce

Install Firefox 60, create a new profile. IT navigates to:

https://www.mozilla.org/en-US/firefox/60.7.0/firstrun

### Expected result

No message (It's the latest ESR)

### Actual result

See message 

### Environment

Windows 10, Firefox ESR

I'm honestly not sure how this can be detected since we don't send the minor version in the user agent. Maybe via UITour?

**Comment by hoosteeno** [comment] 2019-06-14 21:18
I followed the steps to reproduce -- [downloaded a fresh ESR](https://www.mozilla.org/en-US/firefox/organizations/all/), ran `firefox -p` from the command line to create a new profile, and visited the firstrun page (it opened automatically) -- but I could not reproduce. I even modified `privacy.resistFingerprinting` in about.config, as described in https://github.com/mozilla/bedrock/issues/6495, and still could not reproduce.

**Comment by mkaply** [comment] 2019-06-14 21:20
That's really odd. I definitely got it. I'll see if I can recreate again.

**Comment by mkaply** [comment] 2019-06-14 21:34
Interesting. My scenario is weird but I don't know why it would cause a different page to be seen.

1. Install Firefox 52.
2. Start Firefox 52, create a profile, it gets an update.
3. Close Firefox
4. Start Firefox, but create a new profile.
5. Page displays with the upgrade message.

If you explicitly create a new profile, you don't see it. IT only happens when creating a new profile where Firefox is started for the first time after being upgraded from 52?

**Comment by alexgibson** [comment] 2019-07-01 13:03
Given the steps above, this seems like a Firefox profile issue rather than a website bug.

**Comment by mkaply** [comment] 2019-07-01 13:23
Oddly I just saw it again with a fresh 60 profile. So it seems intermittent.

**Comment by alexgibson** [comment] 2019-07-01 13:39
I just tried a fresh profile after downloading ESR 60, and cannot reproduce.

Running `Mozilla.Client.FirefoxDetails` in the console returns the following data, which is as expected:

```
{ 
  accurate: true, 
  version: "60.7.2", 
  channel: "esr", 
  distribution: "default", 
  isUpToDate: true, 
  isESR: true 
}
```

@mkaply can you try the above to see what you get? ^

**Comment by mkaply** [comment] 2019-07-02 18:38
I'm getting:

    { accurate: false, version: "60.0", channel: "release", distribution: undefined, isUpToDate: false, isESR: false }

But it's definitely ESR (I verified the about screen, internal version and update channel)

**Comment by alexgibson** [comment] 2019-07-03 14:18
Ok, let's dig a little deeper here. What's the output when you run this in the console?

```javascript
document.addEventListener('mozUITourResponse', function(event) { console.log(event.detail.data) }, false);
document.dispatchEvent(new CustomEvent('mozUITour', {
    'bubbles': true,
    'detail': {
        'action': 'getConfiguration',
        'data': { 'configuration': 'appinfo', 'callbackID': 123456789 }
    }
}));
```

**Comment by mkaply** [comment] 2019-07-03 14:22
Object { version: "60.7.2", distribution: "default", defaultUpdateChannel: "esr", defaultBrowser: false, canSetDefaultBrowserInBackground: false, profileCreatedWeeksAgo: 0, profileResetWeeksAgo: null }

And I verified that Mozilla.Client.FirefoxDetails

is still

Object { accurate: false, version: "60.0", channel: "release", distribution: undefined, isUpToDate: false, isESR: false }

**Comment by alexgibson** [comment] 2019-07-03 14:52
Ok, we're getting somewhere!

I believe this is a race condition. Our code [waits a total of 400ms](https://github.com/mozilla/bedrock/blob/master/media/js/base/mozilla-client.js#L430-L431) between firing the event and receiving a response from Firefox, before falling back on some default values.

```javascript
// Fire the fallback function in .4 seconds
var timer = window.setTimeout(returnFxaDetails, 400);
```

We do this because UITour has no real form of exception handling (we just ping and hope for a response). It looks like for some reason, when starting a fresh profile on your machine, this 400ms threshold is being exceeded, and that's why you see differing data and intermittent results.

Two possible remedies are:

1.) Increase the timeout value. I'd be hesitant to set this longer than 500ms, but I'd also be curious to benchmark how long the response is taking for you.
2.) Set the notification to only display if `accurate` is `true`. This means the notification will only show if the fallback was not triggered.

Doing both of the above things probably make sense here ^

**Comment by mkaply** [comment] 2019-07-03 14:55
> but I'd also be curious to benchmark how long the response is taking for you.

Any easy way for me to do that, given it's a new profile?

**Comment by alexgibson** [comment] 2019-07-03 14:56
> Any easy way for me to do that, given it's a new profile?

I'll mull this over and try to figure out a way. Thanks

**Comment by alexgibson** [comment] 2019-07-04 14:47
@mkaply I pushed a small patch to demo to try and help measure how long the call is taking. I'm still not quite sure how to test this accurately under new profile conditions, but loading the following URL using Firefox ESR 60 on macOS, I see call times up to around ~100max (over repeated runs), which is well under the current threshold.

https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/firstrun/

Note: to see accurate times you'll need to whitelist UITour for demo with the following pref:

`browser.uitour.testingOrigins` : `https://bedrock-demo-agibson.oregon-b.moz.works/`

**Comment by mkaply** [comment] 2019-07-04 15:00
I can change the default homepage using distribution to that URL.

**Comment by mkaply** [comment] 2019-07-08 15:27
of course in a classic case of measuring affecting the output, I can't recreate with the test site...

**Comment by alexgibson** [comment] 2019-11-28 13:50
This notification is being removed in https://github.com/mozilla/bedrock/pull/8202. Closing this as wontfix.

**Closed by alexgibson** 2019-11-28 13:50 UTC
