### ISSUE TITLE
Dry Market Test Analysis

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6985] opened 2019-03-26 19:50 UTC
## Description

The experiment has ended and now analysis of the resulting data is required.

The original issue for the experiment - #6899
---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Deliver the write up/analysis by EOD Friday March 29th

**Comment by alexgibson** [comment] 2019-03-27 09:39
> The experiment has ended and now analysis of the resulting data is required.

The experiment is [still running in production](https://github.com/mozmeao/www-config/blob/master/waffle_configs/bedrock-prod.env#L22). Does this mean we can shut it off?

**Comment by alexgibson** [comment] 2019-03-29 10:44
Closing as a duplicate of https://github.com/mozilla/bedrock/issues/6995

**Closed by alexgibson** 2019-03-29 10:44 UTC
Labels: Other Projects
