### ISSUE TITLE
CJMS errors during VPN Coupon Promo experiment.

### ISSUE THREAD

**Issue by birdsarah** [mozilla/bedrock#11998] opened 2022-08-03 13:39 UTC
The CJMS sentry logs show a spike in errors between July 11 and July 19 and a smaller spike on July 7 and July 8.

The errors are because bedrock is sending a flow_id it has already sent us and so we are raising a duplicate violation error.

Almost all of these errors stem from bedrock sending "undefined" as a flow_id. Some are for sending a flow id that already existed in our system. I mention this because the "undefined" errors are because it was sent once and then any further attempts to send "undefined" become a duplicate violation.

In initial discussion with @alexgibson the timing coincides with the dates when we ran the experiment https://github.com/mozilla/bedrock/issues/11826 ran.

---

This ticket is to investigate the potential causes of this to make sure we're correctly handling affiliate when experiments are running....(or @alexgibson to better define).

**Comment by alexgibson** [comment] 2022-08-03 13:42
I can reproduce this locally when there's a CJ affiliate param in the URL and the experiment performs a redirect.

Going to try and figure out what's up

**Comment by alexgibson** [comment] 2022-08-03 14:57
OK so what i think is happening here is as follows:

1. The experiment redirect was miss-configured in the page. The JS script that performs the redirect should have been inserted into the `<head>` of the page. Instead, the script was being loaded just before the closing `</body>`. 
2. This meant that the CJMS code was being run prior to the experiment redirect happening, causing the FxA flow param request to fail prematurely, passing `undefined` to the CJMS call.
3. After the redirect finally happens, and the page loads again, the FxA flow param and CJSM call then both happen successfully.

So, I think we just ended up making a bunch of duplicate calls, where the first call threw a 500 error, but the second call was OK.

I'm going to think of some next steps here that we can do to stop this type of error happening in our experiments. But a first and easy fix seems to be stop making CJMS calls if flow params are undefined.

**Closed** 2022-08-11 14:09 UTC
Labels: Bug :bug:
