### ISSUE TITLE
[Refresh] Pencil banner should have a close / dismiss button

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#15374] opened 2024-10-23 14:50 UTC
## Description

The pencil banner should have a close (X) button on the right hand side that can be used to dismiss the banner.

When closed, we should set a preference cookie, in the same way we do for our older (pre-redesign) banners.

---

#### Success Criteria
- [ ] Pencil banner is dismiss-able

**Comment by stephaniehobson** [comment] 2024-10-25 23:06
Duplicate of https://github.com/mozilla/bedrock/issues/15331

**Closed by stephaniehobson** 2024-10-25 23:06 UTC
Labels: Refresh 🦖
