### ISSUE TITLE
Update donation links across mozilla.org

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#12698] opened 2023-02-04 00:23 UTC
## Description

The donation link for MoFo has been updated, and we need to update across mozilla.org

- [ ] Identify bedrock links in [this document](https://docs.google.com/spreadsheets/d/1V9hmlDlJoqOe2AbJ_dMjR5wZ3Iv1z9ZV4Hy1jQ465vc/edit?usp=sharing), and update URL
- [ ] Search bedrock for any additional donation links that we may have missed.

[Document of referrals](https://docs.google.com/spreadsheets/d/1V9hmlDlJoqOe2AbJ_dMjR5wZ3Iv1z9ZV4Hy1jQ465vc/edit?usp=sharing)

Link to replace with: TBD. Reached out to Mofo to advise. 
---

**Comment by slightlyoffbeat** [comment] 2023-02-17 08:42
New URL: https://foundation.mozilla.org/?form=donate

UTM Parameters - lets maintain what was in use for the old links. For any questions or clarifications, reach out to me.

**Comment by alexgibson** [comment] 2023-02-17 09:13
This is possibly a duplicate of https://github.com/mozilla/bedrock/issues/12628 (which has more details about how we should handle passing currency, as well as how to handle the fundraising banner.

**Closed** 2023-02-20 16:04 UTC
Labels: P2
