### ISSUE TITLE
Identify new evergreen content for ROW homepage.

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#9880] opened 2021-01-28 20:26 UTC
## Description

The homepage that most visitors to www.mozilla.org see has not been updated with fresh content for a very long time. Many of the items promoted there are no longer a part of Mozilla's story. We should identify new content for the page. We should use only Protocol elements there, and only publish/link to content that has substantial global coverage. 

---

#### Success Criteria
- [ ] New content identified in a content doc attached
- [ ] New content staged for review in web staging

#### See Also
* https://github.com/mozilla/bedrock/issues/5824
* https://github.com/mozilla/bedrock/issues/8516

**Comment by Ayushsunny** [comment] 2021-01-30 04:25
What's the issue here,
I would like to work on this issue

**Comment by Aayushap1** [comment] 2021-01-30 15:24
Recently, I worked on a web project from where I come to know about github, I fell, I am capable for working on this issue. 
so, I request you to please assign this work to me.

**Comment by alexgibson** [comment] 2023-05-23 16:03
Closing as duplicate of https://github.com/mozilla/bedrock/issues/12282

**Closed by alexgibson** 2023-05-23 16:03 UTC
Labels: Needs Info, Needs Design
