### ISSUE TITLE
The “It's here! Your Firefox mobile download link.” email is not received

### ISSUE THREAD

**Issue by mariaberlinger** [mozilla/bedrock#12157] opened 2022-09-20 12:32 UTC
**Affected FxA versions:**

- 1.241.1;

**Prerequisites:**

- The user signed in to Sync on a computer;

- The user is on the "Get Firefox on your phone or tablet" page with QR code, on desktop;

- Firefox is not installed on mobile;

**Steps to reproduce:**

1. Click the "send yourself a[ download link.](https://www.mozilla.org/firefox/mobile/get-app/)" link;

2. Enter the email address and click "Send" button;

3. Go to email inbox and open the email with the download link;

**Expected result:**

- The “It's here! Your Firefox mobile download link.” email is received;

**Actual result:**

- There is no “It's here! Your Firefox mobile download link.” email received;

**Notes:**

- This is a major issue because it blocks users from receiving the “It's here! Your Firefox mobile download link.” email;

**Comment by alexgibson** [comment] 2022-09-20 13:01
@mariaberlinger I can't reproduce this, when I fill out the form on https://www.mozilla.org/firefox/mobile/get-app/ and click send I receive the email a-OK?

**Comment by alexgibson** [comment] 2022-09-20 13:13
@mariaberlinger can you please provide the email address you tried for testing? I can look it up in the system

**Comment by alexgibson** [comment] 2022-09-22 13:05
It sounds like this was resolved before this bug was filed. Closing as fixed, but please re-open if you still see a problem. thanks

**Closed by alexgibson** 2022-09-22 13:05 UTC
Labels: Needs Info, Bug :bug:
