### ISSUE TITLE
Code according to specification developed to prevent SERPs from displaying browser incompatibility warning on “browser” searches.

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8798] opened 2020-04-20 21:40 UTC
In https://github.com/mozilla/bedrock/issues/8739 we'll specify what needs to change to prevent search engines from picking up browser incompatibility warnings and displaying them in search results. This card is about making code changes as specified.

**Comment by alexgibson** [comment] 2020-04-30 07:53
Closing as a duplicate of 8#739

**Closed by alexgibson** 2020-04-30 07:53 UTC
Labels: P1
