### ISSUE TITLE
Identify 10 S mode users

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6172] opened 2018-09-13 22:36 UTC
Description: Research means to identify 10 S mode users from the mozilla.org website.

Reasoning:  

- Windows 10 in S mode prevents users from installing Firefox
- If successful we could then put this flag in a data attribute that GA would pick to then understand the set of users attempting to download Firefox
- Could provide users with messaging about 'S' mode, including instructions how to disable S mode that would enable them to install Firefox

**Comment by alexgibson** [comment] 2018-11-23 16:18
This is a duplicate of https://github.com/mozilla/bedrock/issues/6367

**Closed by alexgibson** 2018-11-23 16:18 UTC
Labels: Moz.org, Other Projects
