### ISSUE TITLE
Remove deprecated Protocol components

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#10500] opened 2021-09-23 16:47 UTC
## Description

Dump from running `npm start`:

[1] WARNING: Hero component is now deprecated. Please migrate to use Split: https://protocol.mozilla.org/patterns/organisms/split.html
[1]          on line 7 of node_modules/@mozilla-protocol/core/protocol/css/components/_hero.scss
[1]          from line 11 of media/css/mozorg/about.scss

[1] WARNING: Hero component is now deprecated. Please migrate to use Split: https://protocol.mozilla.org/patterns/organisms/split.html
[1]          on line 7 of node_modules/@mozilla-protocol/core/protocol/css/components/_hero.scss
[1]          from line 10 of media/css/mozorg/lean-data.scss

[1] WARNING: Hero component is now deprecated. Please migrate to use Split: https://protocol.mozilla.org/patterns/organisms/split.html
[1]          on line 7 of node_modules/@mozilla-protocol/core/protocol/css/components/_hero.scss
[1]          from line 9 of media/css/firefox/installer-help.scss

[1] WARNING: Hero component is now deprecated. Please migrate to use Split: https://protocol.mozilla.org/patterns/organisms/split.html
[1]          on line 7 of node_modules/@mozilla-protocol/core/protocol/css/components/_hero.scss
[1]          from line 10 of media/css/firefox/testflight.scss

[1] WARNING: Hero component is now deprecated. Please migrate to use Split: https://protocol.mozilla.org/patterns/organisms/split.html
[1]          on line 7 of node_modules/@mozilla-protocol/core/protocol/css/components/_hero.scss
[1]          from line 9 of media/css/firefox/features/picture-in-picture.scss

[1] WARNING: Hero component is now deprecated. Please migrate to use Split: https://protocol.mozilla.org/patterns/organisms/split.html
[1]          on line 7 of node_modules/@mozilla-protocol/core/protocol/css/components/_hero.scss
[1]          from line 13 of media/css/newsletter/newsletter.scss

[1] WARNING: Hero component is now deprecated. Please migrate to use Split: https://protocol.mozilla.org/patterns/organisms/split.html
[1]          on line 7 of node_modules/@mozilla-protocol/core/protocol/css/components/_hero.scss
[1]          from line 10 of media/css/mozorg/home/home.scss

[1] WARNING: Picto Card component is now deprecated. Please migrate to use Picto: https://protocol.mozilla.org/patterns/molecules/picto.html
[1]          on line 7 of node_modules/@mozilla-protocol/core/protocol/css/components/_picto-card.scss
[1]          from line 14 of media/css/mozorg/home/home.scss

[1] WARNING: Hero component is now deprecated. Please migrate to use Split: https://protocol.mozilla.org/patterns/organisms/split.html
[1]          on line 7 of node_modules/@mozilla-protocol/core/protocol/css/components/_hero.scss
[1]          from line 12 of media/css/foundation/annual-report-2019.scss

[1] WARNING: Picto Card component is now deprecated. Please migrate to use Picto: https://protocol.mozilla.org/patterns/molecules/picto.html
[1]          on line 7 of node_modules/@mozilla-protocol/core/protocol/css/components/_picto-card.scss
[1]          from line 9 of media/css/firefox/firstrun/nightly.scss

[1] WARNING: Hero component is now deprecated. Please migrate to use Split: https://protocol.mozilla.org/patterns/organisms/split.html
[1]          on line 7 of node_modules/@mozilla-protocol/core/protocol/css/components/_hero.scss
[1]          from line 12 of media/css/firefox/firstrun/nightly.scss

[1] WARNING: Picto Card component is now deprecated. Please migrate to use Picto: https://protocol.mozilla.org/patterns/molecules/picto.html
[1]          on line 7 of node_modules/@mozilla-protocol/core/protocol/css/components/_picto-card.scss
[1]          from line 14 of media/css/firefox/privacy/common.scss

[1] WARNING: Hero component is now deprecated. Please migrate to use Split: https://protocol.mozilla.org/patterns/organisms/split.html
[1]          on line 7 of node_modules/@mozilla-protocol/core/protocol/css/components/_hero.scss
[1]          from line 9 of media/css/firefox/set-as-default/thanks.scss

[1] WARNING: Hero component is now deprecated. Please migrate to use Split: https://protocol.mozilla.org/patterns/organisms/split.html
[1]          on line 7 of node_modules/@mozilla-protocol/core/protocol/css/components/_hero.scss
[1]          from line 9 of media/css/firefox/new/basic/download.scss

[1] WARNING: Picto Card component is now deprecated. Please migrate to use Picto: https://protocol.mozilla.org/patterns/molecules/picto.html
[1]          on line 7 of node_modules/@mozilla-protocol/core/protocol/css/components/_picto-card.scss
[1]          from line 9 of media/css/firefox/new/basic/platform.scss

[1] WARNING: Hero component is now deprecated. Please migrate to use Split: https://protocol.mozilla.org/patterns/organisms/split.html
[1]          on line 7 of node_modules/@mozilla-protocol/core/protocol/css/components/_hero.scss
[1]          from line 9 of media/css/firefox/channel.scss

[1] WARNING: Hero component is now deprecated. Please migrate to use Split: https://protocol.mozilla.org/patterns/organisms/split.html
[1]          on line 7 of node_modules/@mozilla-protocol/core/protocol/css/components/_hero.scss
[1]          from line 14 of media/css/firefox/pocket.scss

[1] WARNING: Hero component is now deprecated. Please migrate to use Split: https://protocol.mozilla.org/patterns/organisms/split.html
[1]          on line 7 of node_modules/@mozilla-protocol/core/protocol/css/components/_hero.scss
[1]          from line 9 of media/css/firefox/unfck.de.scss

[1] WARNING: Hero component is now deprecated. Please migrate to use Split: https://protocol.mozilla.org/patterns/organisms/split.html
[1]          on line 7 of node_modules/@mozilla-protocol/core/protocol/css/components/_hero.scss
[1]          from line 11 of media/css/firefox/unfck.scss

[1] WARNING: Hero component is now deprecated. Please migrate to use Split: https://protocol.mozilla.org/patterns/organisms/split.html
[1]          on line 7 of node_modules/@mozilla-protocol/core/protocol/css/components/_hero.scss
[1]          from line 9 of media/css/foundation/reimagine-open.scss

[1] WARNING: Hero component is now deprecated. Please migrate to use Split: https://protocol.mozilla.org/patterns/organisms/split.html
[1]          on line 7 of node_modules/@mozilla-protocol/core/protocol/css/components/_hero.scss
[1]          from line 9 of media/css/firefox/sync.scss

[1] WARNING: Hero component is now deprecated. Please migrate to use Split: https://protocol.mozilla.org/patterns/organisms/split.html
[1]          on line 7 of node_modules/@mozilla-protocol/core/protocol/css/components/_hero.scss
[1]          from line 9 of media/css/firefox/set-as-default/landing.scss

[1] WARNING: Hero component is now deprecated. Please migrate to use Split: https://protocol.mozilla.org/patterns/organisms/split.html
[1]          on line 7 of node_modules/@mozilla-protocol/core/protocol/css/components/_hero.scss
[1]          from line 9 of media/css/firefox/features/adblocker.scss

[1] WARNING: Hero component is now deprecated. Please migrate to use Split: https://protocol.mozilla.org/patterns/organisms/split.html
[1]          on line 7 of node_modules/@mozilla-protocol/core/protocol/css/components/_hero.scss
[1]          from line 11 of media/css/firefox/privacy/book.scss

[1] WARNING: Hero component is now deprecated. Please migrate to use Split: https://protocol.mozilla.org/patterns/organisms/split.html
[1]          on line 7 of node_modules/@mozilla-protocol/core/protocol/css/components/_hero.scss
[1]          from line 12 of media/css/firefox/mobile/mobile.scss

[1] WARNING: Hero component is now deprecated. Please migrate to use Split: https://protocol.mozilla.org/patterns/organisms/split.html
[1]          on line 7 of node_modules/@mozilla-protocol/core/protocol/css/components/_hero.scss
[1]          from line 11 of media/css/contentful/general.scss
[1] 
[1] WARNING: Hero component is now deprecated. Please migrate to use Split: https://protocol.mozilla.org/patterns/organisms/split.html
[1]          on line 7 of node_modules/@mozilla-protocol/core/protocol/css/components/_hero.scss
[1]          from line 11 of media/css/contentful/mozilla/c-hero.scss

[1] WARNING: Hero component is now deprecated. Please migrate to use Split: https://protocol.mozilla.org/patterns/organisms/split.html
[1]          on line 7 of node_modules/@mozilla-protocol/core/protocol/css/components/_hero.scss
[1]          from line 11 of media/css/contentful/firefox/c-hero.scss

---

#### Success Criteria
- [ ] Deprecated components are replaced with newer alternatives.

**Comment by maureenlholland** [comment] 2022-06-01 10:28
Closing as duplicate of https://github.com/mozilla/bedrock/issues/11493 (picto cards already removed, hero removal in progress https://github.com/mozilla/bedrock/pull/11687)

**Closed by maureenlholland** 2022-06-01 10:28 UTC
Labels: Papercuts 💸
