### ISSUE TITLE
Replace Lockwise with VPN on /firefox

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#9905] opened 2021-02-04 20:34 UTC
## Description

We have outdated content on our /firefox page, and we don't have a good product ecosystem page. In the near term, we can repurpose the /firefox page to include a modern product ecosystem by swapping lockwise for VPN there.

Why is this a near-term solution?
* Because the page is branded Firefox, and we have non-Firefox-Branded stuff there (we've always had Pocket and now we'll add VPN)

Attached is  a rough mockup explaining the changes to make. Improvements to this are welcome. Analytics specifications to come (@alexgibson can provide if needed).

![firefox-gets-vpn](https://user-images.githubusercontent.com/94519/106951867-8b94d000-66ed-11eb-9b74-cb8cb873908d.png)

---

#### Success Criteria
- [ ] Overall approach vetted by Studio team
- [ ] Design approach vetted by webdev & UX
- [ ] Mockup coded on demo
- [ ] Links have appropriate parameters
- [ ] Launched

**Comment by alexgibson** [comment] 2021-02-04 20:47
Note that there’s only a single subscription link for VPN all clients, so a drop down with options may not strictly be necessary. However, we also need to consider that VPN is not available in all countries just yet, so we can’t really link directly to the subscribe flow. 

My suggestion would be to link to the VPN landing page instead, which contains all the necessary logic for above.

**Comment by hoosteeno** [comment] 2021-02-04 20:56
> Note that there’s only a single subscription link for VPN all clients, so a drop down with options may not strictly be necessary. 

The point of putting them all there is for advertising our platform breadth, not to enable different flows. If we can communicate all the platforms somehow else, great.

> However, we also need to consider that VPN is not available in all countries just yet, so we can’t really link directly to the subscribe flow.

I think we agreed in the VPN l10n meeting recently that figuring out what should happen for a user outside of a geography is logic we want to centralize in the VPN application. If someone outside of launch markets tries to subscribe, the VPN application should get them on a waitlist. But that's not how it works now. 

This will be a problem for other VPN marketing on www, too. Will we copy and maintain a list of launch locales in logic on www for the VPN landing page? 

* If yes, then we should abstract that capability so it is available for other VPN CTAs sitewide
* If no, then we need to solve before VPN launch on www

> 
> My suggestion would be to link to the VPN landing page instead, which contains all the necessary logic for above.

That works, but not optimal.

**Comment by alexgibson** [comment] 2021-02-04 21:23
> Will we copy and maintain a list of launch locales in logic on www for the VPN landing page?

The landing page maintains a list of available countries for VPN, not locales. That’s the way it works today, so we should build toward that for now.

Abstracting this functionality to work on other parts of www is totally do-able too, but that’s for future work that’s still to be planned out.

**Comment by alexgibson** [comment] 2021-06-25 12:08
Closing as a duplicate of https://github.com/mozilla/bedrock/issues/10166

**Closed by alexgibson** 2021-06-25 12:08 UTC
Labels: Duplicate
