### ISSUE TITLE
Get new TrafficCop into Bedrock

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#9290] opened 2020-08-06 20:28 UTC
## Description

TrafficCop has an important bug fix (the ability to distribute fractionally) but hasn't been pulled into Bedrock since that capability was merged. We should bring the latest version in.

---

#### Success Criteria
- [ ] Latest TrafficCop is included in Bedrock

**Comment by alexgibson** [comment] 2020-08-10 07:38
There’s already an issue and pull request for this. Closing as a duplicate of https://github.com/mozilla/bedrock/issues/9209

**Closed by alexgibson** 2020-08-10 07:38 UTC
