### ISSUE TITLE
Change out a placeholder link on Enterprise page

### ISSUE THREAD

**Issue by skrelnick23** [mozilla/bedrock#7668] opened 2019-09-05 15:10 UTC
## Description

There is a link out from the SLA page that goes to a page that was a placeholder. All instance of https://mozilla.force.com/enterprise/s/ replace with https://enterprise-help.mozilla.com/hc/en-us

### Steps to reproduce

All instance of https://mozilla.force.com/enterprise/s/ replace with https://enterprise-help.mozilla.com/hc/en-us

### Expected result

All instance of https://mozilla.force.com/enterprise/s/ replace with https://enterprise-help.mozilla.com/hc/en-us

### Actual result

What happened.

### Environment

What browser and operating system are you using?

**Comment by hoosteeno** [comment] 2019-09-05 16:01
Duplicate of #7667

**Closed by hoosteeno** 2019-09-05 16:01 UTC
