### ISSUE TITLE
WNP 108 (eu)

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#12232] opened 2022-10-12 03:01 UTC
## Description

Placeholder for WNP 108 (EU)

---

#### Success Criteria
- [ ] An element contributing to the definition of done for the card
- [ ] Tasks should be represented here as something like "Approved designs attached to this issue"

**Comment by alexgibson** [comment] 2022-11-22 16:10
Closing as duplicate of https://github.com/mozilla/bedrock/issues/12231

**Closed by alexgibson** 2022-11-22 16:10 UTC
