### ISSUE TITLE
https://www.mozilla.org/en-US/contribute/ links to a 404 MDN page

### ISSUE THREAD

**Issue by peterbe** [mozilla/bedrock#10340] opened 2021-07-19 20:20 UTC
## Description

https://www.mozilla.org/en-US/contribute/ links to https://developer.mozilla.org/docs/Mozilla/Developer_guide/Introduction/?utm_source=mozilla.org-contribute&utm_medium=referral&utm_campaign=contribute-page which does not exist anymore. 

### Steps to reproduce

^

### Expected result

A better URL that welcomes people to contribute to mozilla-central. Perhaps @sylvestre knows? :)

### Actual result

https://developer.mozilla.org/docs/Mozilla/Developer_guide/Introduction/ is archived content that no longer is rendered or hosted by MDN.

**Comment by peterbe** [comment] 2021-07-19 20:20
<img width="585" alt="Screen Shot 2021-07-19 at 4 20 19 PM" src="https://user-images.githubusercontent.com/26739/126222041-b05dd785-0730-4de1-ac90-5d630e7e9f0a.png">

**Comment by jwhitlock** [comment] 2021-07-19 21:05
Dupe of #10244

**Comment by alexgibson** [comment] 2021-07-27 09:20
Closing as a dupe of #10244, but thanks for filing 👋

**Closed by alexgibson** 2021-07-27 09:20 UTC
Labels: Bug :bug:
