### ISSUE TITLE
remove the current zh-TW whatsnew template and follow the global one

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7130] opened 2019-04-30 20:07 UTC
## Description

https://bugzilla.mozilla.org/show_bug.cgi?id=1545705

So please help us remove the current zh-TW whatsnew template:
https://www.mozilla.org/zh-TW/firefox/whatsnew/

And follow the global one instead,
so that users would be able to get the latest updates.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] This is an example of a success criteria. Use a checklist!
- [ ] This is an example of a success criteria.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [ ] This is an example of a task. Use a checklist!
- [ ] This is an example of a task.

**Comment by alexgibson** [comment] 2019-05-23 16:29
Closing as a duplicate of https://github.com/mozilla/bedrock/issues/7211

**Closed by alexgibson** 2019-05-23 16:29 UTC
