### ISSUE TITLE
German: Firefox Nightly Firstrun page contains obsolete links

### ISSUE THREAD

**Issue by peiying2** [mozilla/bedrock#9930] opened 2021-02-16 19:13 UTC
## Description

Check the discussion here: https://bugzilla.mozilla.org/show_bug.cgi?id=1692600

Though firefox/nightly/firstrun.ftl has been migrated, https://github.com/mozilla/bedrock/blob/master/bedrock/firefox/templates/firefox/nightly/firstrun.de.html is a hardcoded page which contains obsolete links. 

### Expected result

Either remove the template, and resort to the page offered to the other locales. The page in Pontoon is already localized. OR update the hard coded page and remove the links stated in bug https://bugzilla.mozilla.org/show_bug.cgi?id=1692600

**Comment by Archaeopteryx** [comment] 2021-02-17 09:15
Recommendations:

Drop:
* @mozilla_deutsch
* Facebook
* Aktuelle Veranstaltungen - could be added again when they resume.

Replace:
* "www.mozilla.de" > "Mozilla-Neuigkeiten von Sören Hentzschel" linking to https://www.soeren-hentzschel.at/
* "IRC-Chat: #mozilla.de" with "Element-Chat: #mozilla.de" linking to https://chat.mozilla.org/#/room/#mozilla.de:mozilla.org
* "Mailing-Liste" > "Forum der Gemeinschaft" with link to https://discourse.mozilla.org/c/communities/germany/59

The text above should get a small modification:

Old:
```
Unsere Projekte bieten einige vielfältige Möglichkeiten, wie sich wirklich jeder aktiv einbringen kann: Helfen Sie Anwendern von Mozilla-Software, arbeiten Sie an der Übersetzung der Mozilla-Software von Webseiten mit oder planen Sie Veranstaltungen für das WebMaker-Projekt.
```

New:
```
Unsere Projekte bieten einige vielfältige Möglichkeiten, wie sich wirklich jeder aktiv einbringen kann: Helfen Sie Anwendern von Mozilla-Software oder arbeiten Sie an der Übersetzung der Mozilla-Software und -Webseiten mit.
```

Can create a pull request later.

**Comment by alexgibson** [comment] 2021-02-19 17:17
Pull requests are always welcome if anyone in the community would like to make these updates

**Comment by PFischbeck** [comment] 2021-02-23 16:38
I am working on a PR to resolve this. However, in the process I have noticed that there is an invisible `h3`, which I have partially highlighted here:
![hidden-h3](https://user-images.githubusercontent.com/2820802/108875229-3b7aa080-75fd-11eb-9fa9-37de7e5c0579.png)

The same issue appears with custom `firstrun` pages of other locales. What is the correct fix for this? Add `mzp-t-dark` to the `div` for every affected locale?

**Comment by alexgibson** [comment] 2021-02-23 17:16
> The same issue appears with custom firstrun pages of other locales. What is the correct fix for this? Add mzp-t-dark to the div for every affected locale?

Good catch! Looks like this is a regression from a recent Protocol update that changed the way pages do theming. Adding a class of `mzp-t-dark` to the `.locale-specific` container DIV seems like a quick and simple enough solution to me.

**Closed** 2021-02-24 00:59 UTC
Labels: Bug :bug:
