### ISSUE TITLE
[9/17] MOSS updates

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#5764] opened 2018-05-30 16:43 UTC
[New updates to MOSS site](https://docs.google.com/document/d/1As5KUmbvF9TTlGn_BvPxcf4fo9Mgk-9WVzaK4yENLMI/edit?ts=5b893b09)

**Comment by alexgibson** [comment] 2018-07-28 11:21
Duplicate of #5765

**Comment by ejregithub** [comment] 2018-07-28 20:34
Not a dupe. There are quarterly updates MOSS wants. This was supposed to go on July 20th but has been delayed with the comment that the request is forthcoming, thus the subject line change from July 20th to TBD

**Comment by alexgibson** [comment] 2018-07-28 20:46
This is the exact same google doc linked in the other issue, so without any further info in the description it wasn’t clear what this was for. Thanks

**Closed** 2018-10-02 18:13 UTC
Labels: Other Projects, 🗃️Project
