### ISSUE TITLE
Locale info returned in search results for "Mozilla"

### ISSUE THREAD

**Issue by maureenlholland** [mozilla/bedrock#12328] opened 2022-11-04 13:17 UTC
Likely related to https://github.com/mozilla/bedrock/pull/12224/files

![locale-title](https://user-images.githubusercontent.com/19650432/199981325-4b7532c2-9849-489b-a328-42f29b701ee3.png)

We want to keep mozorg info for search result title and description. Currently, search results are returning locale 404 info in certain geos (i.e. France and Germany).

**Comment by maureenlholland** [comment] 2022-11-04 13:25
I cannot recreate this from UK. I can recreate with a VPN connection from Paris, France.
<img width="758" alt="recreation" src="https://user-images.githubusercontent.com/19650432/199983270-e18b28d6-7ac8-4dbe-86c2-cc259b9e2d77.png">

**Comment by alexgibson** [comment] 2022-11-04 13:29
Same, UK seems OK.

I can reproduce it from Germany via VPN as well however

**Comment by reemhamz** [comment] 2022-11-04 13:44
I can reproduce form Canada but it's seem after some scrolling:
<img width="858" alt="Screen Shot 2022-11-04 at 9 44 12 AM" src="https://user-images.githubusercontent.com/42309026/199987185-eeb4dc0d-15d7-40aa-93bc-9e7b999bad2e.png">

**Comment by maureenlholland** [comment] 2022-11-04 13:59
Worth noting that, if I click the "Choose your language" link, it redirects me to the en-US home page, not a 404 locale page

**Comment by stevejalim** [comment] 2022-11-04 14:06
> Worth noting that, if I click the "Choose your language" link, it redirects me to the en-US home page, not a 404 locale page

I guess the only human users who would actually see this page are ones whose locales we don't yet support, then, else their browser will do what yours did and provide a viable locale.

**Comment by alexgibson** [comment] 2022-11-04 14:09
> I guess the only human users who would actually see this page are ones whose locales we don't yet support, then, else their browser will do what yours did and provide a viable locale.

Looking at https://github.com/mozilla/bedrock/pull/12224/ the behaviour seems to occur if there's no language header set, which would be why we're seeing this in search (IIUC?). I believe we still redirect to `en-US` for unsupported or untranslated locales, as that's what our l10n community seems to prefer.

**Comment by alexgibson** [comment] 2022-11-04 14:12
> I believe we still redirect to en-US for unsupported or untranslated locales, as that's what our l10n community seems to prefer.

Oh, I stand corrected, we do seem to show this page is a locale is unsupported as well.

**Comment by a-kyne** [comment] 2022-11-04 14:32
The expected Google behavior is that the top listing for 'mozilla' in each locale should be the locale home page, not the default domain URL with "Choose your language" that we're seeing on Google.com. 

I have no idea why Google would ever have gotten a 404 for the en-US URL; I doubt they actually did. The listing on Google.com is probably screwed up because of our long history of redirecting the domain default to /en-US/ whenever they crawled it (because of our previous localization response). Since we were using the 302 Temporarily Moved redirect, we had been informing them that the content on /en-US/ was the correct content for the default domain, and that it was just temporarily hosted at /en-US/. 

The other locales that I have tested (google.fr and google.de) show the locale home page URL and the expected behavior.
![image](https://user-images.githubusercontent.com/104653010/199998187-5a6bcee0-d8dd-4df9-b682-e7f74afa93de.png) 
![image](https://user-images.githubusercontent.com/104653010/199998324-6aff758c-4624-400c-8a91-84f64f0a90c8.png)

They don't trust us yet, and they don't trust that we've implemented our hreflang tags correctly. (They don't trust _anyone_ to do it correctly, because many _many_ websites do not).

Let's give it a few more days for them to figure it out and trust us that what we're sending them isn't an error. If it's not fixed next week, we can take alternative actions.

**Comment by robhudson** [comment] 2022-11-04 14:40
> I believe we still redirect to en-US for unsupported or untranslated locales, as that's what our l10n community seems to prefer.

I just tested and we show the locale selection page for unsupported locales. I removed all languages in my browser settings and chose `ach`, which we don't support, and get shown the locale selection page as a 200 response.

@a-kyne Is that what we want for SEO? ⬆️

**Comment by pmac** [comment] 2022-11-04 15:27
It seems Google is just happy with the locale selection page as our home page. Should we just put the OG tags from the english home page on that template so at least the info on the search result page is useful?

**Comment by a-kyne** [comment] 2022-11-04 15:41
@robhudson No--We should not return a 200 response for a URL cannot produce the requested HTML document, and we should not return a 200 for a URL that produces a duplicated document, as in the example that you gave .../ach/. 

Rule number one of SEO is that there should be _one and only one URL_ (one unique string) for any one HTML document. 

But in this case--you didn't follow a link from anywhere, right? You just made up that URL? We should change our response for nonexistent URLs to a 404, but it's not as urgent as if we were actually linking to that URL from somewhere; Googlebot doesn't make up URLs to try, it only follows existing links.

To be clear, our localization strategy causes us to use links to document that have not yet been translated (e.g. the "Assistance" links in Firefox FR that link to the US SuMo pages). Whenever we link to a document that doesn't actually exist and then redirect requests to the en-US version, we are confusing Googlebot and privileging the en-US site. It is to partly mitigate this issue that the new "Choose your language" page has been published. The best practice for SEO is to only link to URLs that produce the content being requested.

**Comment by a-kyne** [comment] 2022-11-04 15:48
> It seems Google is just happy with the locale selection page as our home page. Should we just put the OG tags from the english home page on that template so at least the info on the search result page is useful?

That won't fix the en-US listing; they're using the 404 page metadata because they're confused. Once they are no longer confused, they'll use the metadata from the en-US page for the en-US listing.

**Comment by pmac** [comment] 2022-11-04 15:48
So we do nothing?

**Comment by a-kyne** [comment] 2022-11-04 15:49
Yes. Give them a couple of days and they'll figure it out.

**Comment by pmac** [comment] 2022-11-04 15:58
Okay

**Comment by robhudson** [comment] 2022-11-04 15:58
It sounds like for this specific case we need to make a change...

> When a user has an unsupported locale set in their `accept-language' header, they get a 200 response for the locale selection page. Based on what [you shared](https://github.com/mozilla/bedrock/issues/12328#issuecomment-1303780369) that is bad.

We have 2 options that I see:
1. Redirect unsupported locales in the `accept-language` header to `/en-US/`. (previous behavior)
2. Return the locale selection page but with a 404 response.

**Closed by pmac** 2022-11-04 15:58 UTC
Labels: L10N, SEO

**Comment by a-kyne** [comment] 2022-11-04 16:49
@robhudson The problem here is that we are serving the Choose page with more than one URL, creating duplicate content. I think it's fine to follow our localization pattern for the rest of the site, i.e. redirect the request. 

There shouldn't _be_ any home page requests for locales that we haven't translated yet, since a _person_ would have to modify the URL to do that. A search bot will only follow links, and we shouldn't have any links to locales that haven't been translated. It is fine to redirect requests for non-existent home page translations to the en-US page, because only human beings will submit those requests, not bots.
