### ISSUE TITLE
Show WNP to *beta* channel for users coming from <73.0

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8447] opened 2020-01-15 19:21 UTC
## Description

Show a WNP to beta channel users updating the 73 beta (on RC week)

https://bugzilla.mozilla.org/show_bug.cgi?id=1609507

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Content from a previous rapid release WNP is assigned to the beta URL
- [ ] All locales at 100% are included
- [ ] QA has tested

#### Approvals
- [ ] Team Lead
- [ ] Approving stakeholder (MWarther)

**Comment by alexgibson** [comment] 2020-02-05 15:21
Closing this as a duplicate of https://github.com/mozilla/bedrock/issues/8450 (we missed the boat for beta 73)

**Closed by alexgibson** 2020-02-05 15:21 UTC
