### ISSUE TITLE
unfck A/B test: review convert.com test & direct traffic

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#9542] opened 2020-10-13 22:17 UTC
## Description

A test has been created on convert.com. It is an a/b test with a single variant. This test needs to be reviewed. Once reviewed, we need to direct traffic to it.

An exp template has already been created.

Convert test:
https://app.convert.com/#/projects/1003343/experiments_report/10039917

Test Plan (100% distribution, EN audience):
https://docs.google.com/document/d/1KVBNBF-NS_Jb6wTk0KAHMVmVvs-u7LCkjEPWTE_uJFs/edit?usp=sharing

---

#### Success Criteria
- [x] Review & convert.com code
- [x] Review & convert.com goals
- [x] Once reviewed, pause test, add mozilla.org to target domain
- [x] turn on test.

**Comment by alexgibson** [comment] 2020-10-14 08:45
Code feedback:

What you have works, but the variation is copying / pasting images that reference stage and not production. Rather than replicating all the markup again, something like the following might be simpler / cleaner:

```javascript
var $item = $('#share').remove();
$item.insertBefore('#poli');
```

**Comment by alexgibson** [comment] 2020-10-14 08:54
Noticed a bug: When entered into the `Share as #1` variation, clicking a share link opens the page in a new tab, and not a popup window:

<img width="1678" alt="image" src="https://user-images.githubusercontent.com/400117/95966420-02d2eb00-0e03-11eb-80c5-4a1edd8041e7.png">

I think this is happening because you're adding new content to the DOM after the page JS has bound event listeners. This will also likely effects measurement in GA.

Changing the code to the example in the comment above might help to mitigate the problem.

**Comment by alexgibson** [comment] 2020-10-14 09:01
Goal tracking:

The share CTA goal isn't firing when I click either of the links. i think the issue is because it's looking for a direct descendant, so should be `#share A` instead of `#share > A`?

**Comment by alexgibson** [comment] 2020-10-14 09:03
@slightlyoffbeat I've finished review on this for now. There are a couple of bugs / issues that I think need addressing before we can enable traffic. Let me know if you have any questions / want to chat. Thanks

**Comment by alexgibson** [comment] 2020-10-14 09:59
@hoosteeno i should also probably point out that if the ask is to redirect 100% of traffic to the /exp/ page, then that’s likely going to cause some reporting dashboard somewhere to flatline. We should make sure those invested in analytics are aware.

**Comment by slightlyoffbeat** [comment] 2020-10-14 15:37
@alexgibson awesome thank you. I'll make the recommended changes and update here when I do. I tested the share goal and I recall seeing the event coming through, but I'll revisit.

**Comment by hoosteeno** [comment] 2020-10-14 15:39
Please note: We should hold merging/launching this until we have clarity about a couple questions re: the experiment plan.

1) 100% for a week or 50% for 2 weeks?
2) Start date/time as relates to page content updates?
3) In sandbox or on prod page?

We hope to be able to answer these after marketing standup today.

**Comment by slightlyoffbeat** [comment] 2020-10-14 16:23
@alexgibson changes are made. I changed the goal to `#share A` and I see goal clicks coming through on the live dashboard.

The javascript change is much cleaner and on testing, the share links now work as pop-ups. There is a very slight flash (something that is hard to avoid completely with A/B tests) but I believe most won't notice.

**Comment by alexgibson** [comment] 2020-10-14 16:39
@slightlyoffbeat code changes look good, and evens seem to be in order 👍 

r+ on the experiment code, but let's wait to resolve https://github.com/mozilla/bedrock/issues/9542#issuecomment-708485919

**Comment by hoosteeno** [comment] 2020-10-14 20:41
Answers as of today:

> * 100% for a week or 50% for 2 weeks?
100% for a week.

> * Start date/time as relates to page content updates?
10/20, to be confirmed 10/19.

> * In sandbox or on prod page?
Suggest on prod page to avoid 2 classes of concern:
1) Redirecting 100% of traffic to sandbox will almost certainly break some metrics somewhere. 
2) The timing overlaps CDN replacement, which means our trad'l method of enrollment (using CDN workers) is not predictable

**Comment by alexgibson** [comment] 2020-10-15 08:12
Filed https://github.com/mozilla/bedrock/issues/9549 to address https://github.com/mozilla/bedrock/issues/9542#issuecomment-708648477

**Comment by alexgibson** [comment] 2020-10-19 13:08
I opened a PR to enable convert (and the phase 2 unfck content) on stage: https://github.com/mozmeao/www-config/pull/312

@slightlyoffbeat once the PR linked here has been reviewed and merged you should be unblocked on reconfiguring this experiment. Note we have removed the `/exp/firefox/unfck/` page URL and put Convert directly on `/firefox/unfck/`.

If you have any questions here please give me a shout, thanks.

**Comment by alexgibson** [comment] 2020-10-19 15:29
The new content is now live in prod, so this is unblocked: https://www.mozilla.org/en-US/firefox/unfck/

**Comment by slightlyoffbeat** [comment] 2020-10-19 19:57
Test is updated. Sent to Eddie for review and approval.

@alexgibson the code has a very minor change to accommodate new design.

https://www.allizom.org/en-US/firefox/unfck/?_conv_eforce=10039917.100378480

**Comment by slightlyoffbeat** [comment] 2020-10-19 22:57
@alexgibson Received feedback that requested the share item be above the headline. I made a change that makes everything a bit more narrow, but it looks fine. The only issue (to me) is the use of the heart WIFI image twice in a row. I'm not sure if there is an unused image asset that we an utilize, or if we need a design review on this?

**Comment by slightlyoffbeat** [comment] 2020-10-19 23:26
spent more time thinking about this, and updated to remove heart WIFI image and replace with the computer/cat GIF. Had to do it all with JS in order to avoid larger changes to the way the test is set up.

**Comment by alexgibson** [comment] 2020-10-20 13:24
@slightlyoffbeat code changes look good - one nit: please make sure image sources use www.mozilla.org instead of www.allizom.org.

One other thing I noticed is the alt text still says: `A heart sharing love like a router shares wifi.`, which is now incorrect. I'd say it's not a blocker for the experiment though.

The goal set up looks good, and is working as expected.

r+wc

**Comment by alexgibson** [comment] 2020-10-20 15:40
PR to enable the test in production (do not merge until the above comment has been addressed) https://github.com/mozmeao/www-config/pull/316

We'll also need to update the staging URL to match prod for the experiment.

**Comment by slightlyoffbeat** [comment] 2020-10-20 16:42
@alexgibson Changes are made.

**Comment by alexgibson** [comment] 2020-10-21 07:57
This experiment went live in production yesterday

**Closed by alexgibson** 2020-10-21 07:57 UTC
Labels: CRO, Greenlit Pitch
