### ISSUE TITLE
Unable to run repo using Apple Silicon (probably?)

### ISSUE THREAD

**Issue by tomyumm-ge** [mozilla/bedrock#14587] opened 2024-05-20 14:43 UTC
## Description

I'm facing trouble to run **assets** container. It's stopping on 60% and not doing something else:

<img width="1512" alt="Снимок экрана 2024-05-20 в 17 32 52" src="https://github.com/mozilla/bedrock/assets/18268746/51a5f183-ec22-4b37-9178-ea05eaa149fe">

It's also consumes full 1 CPU core, but nothing happens even after an hour of payload:

<img width="1033" alt="Снимок экрана 2024-05-20 в 17 42 12" src="https://github.com/mozilla/bedrock/assets/18268746/6518275e-d656-490f-aab5-a3ddf7ded9ae">

### Steps to reproduce

**Requires:**
- Macbook M1-3 (probably?)
- Actual repo, master branch

**What to do:**
```bash
cd bedrock
make clean install
```

### Expected result

2 running containers with container 'assets' and compiled webpack modules in it

### Actual result

```log
assets-1  | <s> [webpack.Progress] 59% building 364/408 entries 1269/1304 dependencies 701/788 modules
```

### Environment

- Safari/Google Chrome/Firefox browsers are tested
- macOS Sonoma 14.4.1 (23E224)
- M3 Max processor

### Notes

I'm really sorry if I doesn't met issue design/category requirements, it's my first impulse to contribute to open source

**Comment by alexgibson** [comment] 2024-05-20 14:45
@tomyumm-ge have you tried unchecking `Use Rosetta for x86_64/amd64 emulation on Apple Silicon` in Docker settings?

**Comment by tomyumm-ge** [comment] 2024-05-20 14:55
@alexgibson No, I didn't

I've tried this right now, and it's working, thank you!

But I got some errors for now after entire process was done:

```
WARNING in webpack performance recommendations: 
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/

ERROR in ./media/js/glean/elements.es6.js 8:0-52
Module not found: Error: Can't resolve '../libs/glean/element.js' in '/app/media/js/glean'
resolve '../libs/glean/element.js' in '/app/media/js/glean'
  using description file: /app/package.json (relative path: ./media/js/glean)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: /app/package.json (relative path: ./media/js/libs/glean/element.js)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /app/media/js/libs/glean/element.js doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /app/media/js/libs/glean/element.js.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        /app/media/js/libs/glean/element.js.json doesn't exist
      .wasm
        Field 'browser' doesn't contain a valid alias configuration
        /app/media/js/libs/glean/element.js.wasm doesn't exist
      as directory
        /app/media/js/libs/glean/element.js doesn't exist
 @ ./media/js/glean/init.es6.js 10:0-59 61:6-17

ERROR in ./media/js/glean/page.es6.js 8:0-46
Module not found: Error: Can't resolve '../libs/glean/page.js' in '/app/media/js/glean'
resolve '../libs/glean/page.js' in '/app/media/js/glean'
  using description file: /app/package.json (relative path: ./media/js/glean)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: /app/package.json (relative path: ./media/js/libs/glean/page.js)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /app/media/js/libs/glean/page.js doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /app/media/js/libs/glean/page.js.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        /app/media/js/libs/glean/page.js.json doesn't exist
      .wasm
        Field 'browser' doesn't contain a valid alias configuration
        /app/media/js/libs/glean/page.js.wasm doesn't exist
      as directory
        /app/media/js/libs/glean/page.js doesn't exist
 @ ./media/js/glean/init.es6.js 9:0-78 33:2-25 58:6-16

webpack 5.91.0 compiled with 2 errors and 3 warnings in 132662 ms
```

**Comment by alexgibson** [comment] 2024-05-20 15:03
That's some progress at least! 

The other error seems unrelated to this issue, but is probably because you have not built the assets for Glean.

Can you try `make clean run` instead?

**Comment by tomyumm-ge** [comment] 2024-05-20 15:20
You're right, at least webpack compilation now completes, thank you for that

I've tried `make clean run`, yes, already twice, but error is still here

Am I need to do some additional steps to install glean? Or it must done automatically from package.json or something like that?

**Comment by alexgibson** [comment] 2024-05-20 15:24
Hmm, it should be done as part of `make run`. Perhaps you have an incomplete image. Could you try running `make build` perhaps?

**Comment by tomyumm-ge** [comment] 2024-05-20 21:25
What I did:

- Reboot
- `docker system prune -a`
- `make clean pull build`
- All stages made success
- `make run`

Still exactly the same *glean* error here 😔

**Comment by alexgibson** [comment] 2024-05-21 11:19
Hmm this is a bit odd. I would expect that glean error to happen if [this NPM script](https://github.com/mozilla/bedrock/blob/main/package.json#L73) hadn't run. But that is happening as a pre step already for both `npm start` and `npm build`.

**Comment by stevejalim** [comment] 2024-05-21 11:46
What happens if try first building the `assets` container in isolation? eg with `docker compose build assets` then `make build` then `make run` ?

**Comment by stevejalim** [comment] 2024-05-21 12:01
Also, digging a bit here:
1) Can you provide a full traceback of your build output? Redact sensitive hostnames/usernames if needed and pop it all in a gist maybe?
2) You've referred to `master` branch here, but there is no `master` for Bedrock. Do you mean `main` or are you using a fork/mirror of an old version (~2 years old)
3) You refer to `make ... install` but that's not a command in our makefile. Is that a typo? 
4) What hardware are you on, please?
5) What version of MacOS and Docker are you using, please?

**Comment by alexgibson** [comment] 2024-05-21 12:07
@tomyumm-ge I've managed to reproduce this locally. We'll take a look at figuring out a fix, thank you

**Comment by alexgibson** [comment] 2024-05-21 14:52
@tomyumm-ge this should be resolved by https://github.com/mozilla/bedrock/pull/14592. Thanks for filing a bug!

**Closed** 2024-05-21 16:32 UTC
Labels: Bug :bug:
