### ISSUE TITLE
Add download CTA to /system-requirements/ page

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6051] opened 2018-08-20 16:20 UTC
https://www.mozilla.org/en-US/firefox/61.0.2/system-requirements/

**Comment by rraue** [comment] 2018-08-20 16:37
<img width="1402" alt="screen shot 2018-08-20 at 18 31 45" src="https://user-images.githubusercontent.com/36700618/44353476-607b7f00-a4a7-11e8-9868-c61798142fe6.png">

All system-requirements pages have ca. 180k pageviews a month overall as a landingpage and ca. 20k pageviews via search but the conversion rate is only 1% because there is no download button on this page. The link to firefox/new is very small as well.

- [ ] To test if this is a download opportunity, we should just add a download button visible in the first screen to all sr pages an see if makes sense to update the design/language as well. This should be done for /android/xxx/system-requirements/ as well.

- [ ] We should fix the duplicate titles of /andoid/ and the desktop version, I will file an issue for this. That's how I found the missing download button.

Whats the best but effortless way to do this @dzingeek ? I think it gets obvious here again, that we need a real firefox/all/ page, not just for languages but for all versions, all systems and all languages we could additional to the download button link to on such pages because the download will not solve the problem of every user.

**Comment by alexgibson** [comment] 2018-08-28 09:47
This seems like a good opportunity, but we should also take stock of the existing user flow this page presents. GA may give us some better clues, but I think a good % of users who come to this page are likely on outdated systems that Firefox no longer supports. If we detect such a system for example, instead of seeing a download button users see this:

<img width="282" alt="screen shot 2018-08-28 at 10 40 09" src="https://user-images.githubusercontent.com/400117/44715174-041fed00-aaaf-11e8-88d5-2c5f30cc745d.png">

The link in this message goes to the system requirements page, so sending visitors in a loop is probably something we should try and avoid. Thinking about the design / language we use here is a good idea.

**Comment by stephaniehobson** [comment] 2019-06-26 17:57
I just updated these pages to use Protocol.

![Screenshot_2019-06-25 Firefox 57 0 System Requirements](https://user-images.githubusercontent.com/854701/60202834-4e254c80-9800-11e9-9679-b014b1bad3ed.png)

Proposal:

- Only add *footers* for now. This is the fastest/easiest thing to add because it does not change the design of the page.
- On the Android Systems Requirements pages link to the Play store with the text "Get the most recent version" (As we do on the [Release Notes](https://www.mozilla.org/en-US/firefox/android/60.0.2/releasenotes/))
- On the Firefox Release pages, add the "Get the most recent version" and hide it from systems classified as "old mac", "old windows", or "other".
- Don't add anything to Nightly or Beta pages for now (this is a fair amount of work, we can do it if the initial work pays off).

**Comment by alexgibson** [comment] 2020-03-11 10:39
Closing this as a duplicate of https://github.com/mozilla/bedrock/issues/8647

**Closed by alexgibson** 2020-03-11 10:39 UTC
Labels: Fx Growth Teams, Moz.org
