### ISSUE TITLE
Update Navigation card under About to something more relevant

### ISSUE THREAD

**Issue by djst** [mozilla/bedrock#6518] opened 2018-11-27 12:43 UTC
The current nav card on the About megamenu shows a blurb about the Mozilla Festival, which is a month old now. Let's update this to something relevant - may I propose the EOY fundraising campaign?

![image](https://user-images.githubusercontent.com/5638050/49082618-805ed380-f24a-11e8-83de-301a0413cc4b.png)

**Comment by alexgibson** [comment] 2018-11-27 13:53
I think this is a duplicate of https://github.com/mozilla/bedrock/issues/6471

**Closed by alexgibson** 2018-11-27 13:53 UTC
Labels: Moz.org
