### ISSUE TITLE
Overflowing Navbar Content

### ISSUE THREAD

**Issue by SeanPrashad** [mozilla/bedrock#5515] opened 2018-03-17 03:37 UTC
Accessing the [Branding](https://mozilla.ninja/) option from the [Style guide](https://www.mozilla.org/en-US/styleguide/) shows the contents of the navbar overflowing as shown below:

![mozilla_ninja_bug](https://user-images.githubusercontent.com/13009507/37551261-efa3431c-2972-11e8-8cb8-be30b216f17a.gif)

Edit: The problem occurs at a screen dimension of **1710** x **480**.

**Specs**:

Firefox Quantum - Version 59.0.1 (64-bit)
macOS High Sierra - Version 10.13.3

**Comment by cyclopaman** [comment] 2018-03-17 13:58
It works perfectly well on my computer

**Comment by SeanPrashad** [comment] 2018-03-17 15:38
@cyclopaman Can you state your OS, FF version as well as screen dimensions?

**Comment by flodolo** [comment] 2018-03-17 16:05
Having said that, that [website](https://mozilla.ninja/) is not www.mozilla.org, so the issue is filed in the wrong repository. Still trying to figure out where that website lives.

**Comment by flodolo** [comment] 2018-03-17 16:08
It looks like a bug was already filed on Bugzilla
https://bugzilla.mozilla.org/show_bug.cgi?id=1404932

Thanks for reporting, I'm closing this issue at this point.

**Closed by flodolo** 2018-03-17 16:08 UTC
