### ISSUE TITLE
[Research] Detect Windows 10 app recommendation setting

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/bedrock#9317] opened 2020-08-18 23:26 UTC
## Description

There is currently an issue on Windows 10 where a screen is shown to users saying: 
> To help protect your PC, we suggest you get a Microsoft-verified app

![win10](https://user-images.githubusercontent.com/30483988/90575025-50b6d400-e16f-11ea-8af1-73a8aeb8692c.jpeg)

We should explore if this is something we can detect client-side so we can display custom messaging for these users. 

This setting can be configured in Windows 10 in the [app recommendation settings.](https://support.microsoft.com/en-us/help/4458596/windows-10-change-your-app-recommendation-settings) The tool that stores the setting calls it **AppControlLevel** and the value where it's stored in the registry is called **AicEnabled**

**Comment by amychurchwell** [comment] 2020-08-18 23:57
[There does not appear to be a relevant query string](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/mt795399%28v%3dvs.85%29) for `getHostEnvironmentValue()` to return the value of this user setting. It's also not clear to me if this is a maintained method.

**Comment by alexgibson** [comment] 2020-08-24 08:43
One thing to note here is this seems to be an OS-wide setting, as opposed to a browser setting. With this in mind, the screen shot above may be possible in multiple browsers when trying to download, so a JS API that works everywhere may be unlikely.

**Comment by alexgibson** [comment] 2020-08-24 09:03
OK, I can reproduce this on my windows 10 laptop using Edge by [changing my settings](https://support.microsoft.com/en-us/help/4458596/windows-10-change-your-app-recommendation-settings). The interrupt dialog appears after double clicking the installer, and I was able to trigger it using Edge, Firefox, and Chrome - so it's not just a browser behaviour.

I wonder if there's any way the stub installer could do some detection here?

**Comment by amychurchwell** [comment] 2020-08-27 21:48
Apologies if the title was confusing, this is a setting unrelated to the browser. Wanted to document the conditions which the screenshot occurred.

**Comment by skrelnick23** [comment] 2020-09-10 17:33
I see that we were able to reproduce the message, do we need to huddle and create a new issue to find a way to circumvent this message?

**Comment by alexgibson** [comment] 2020-09-10 17:42
From a website perspective I’m not sure there is a way we can strictly circumvent it. We could provide messaging to help guide users through the process however.

**Comment by skrelnick23** [comment] 2020-09-10 17:52
This is what I was thinking, messaging on the download page. Let me think
through all the ways we need to combat this to ensure our download numbers
aren't hurting.

**Comment by alexgibson** [comment] 2021-05-28 12:55
Closing this. We determined this setting is not possible to detect via a browser API that is exposed to web pages.

**Closed by alexgibson** 2021-05-28 12:55 UTC
